### PR TITLE
allow using tabs

### PR DESCRIPTION
**Pull request by phiresky**
untested, needs release of new psqlformat version with https://github.com/bradymholt/psqlformat/pull/19

### CODE REVIEW

**Comment by bradymholt** [comment]
@phiresky - I published [psqlformat 1.6.0](https://www.npmjs.com/package/psqlformat/v/1.6.0) which should have the tab change.  If you can update the version here the tests should pass and I can release a new version.

**Comment by phiresky** [comment]
as is, this will change the default behaviour (in the _Formatting SQL_ test) to also use Tabs since it uses the workspace FormattingOptions property insertSpaces which is determined by the workspace and files themselves and is apparently false in the test workspace. is that ok?

**Comment by bradymholt** [comment]
@phiresky - Thank you.  I just pushed up https://github.com/bradymholt/vscode-pgFormatter/commit/ad19ec3a53f04bf23b5166bf8d5a45d2c487d2ee#diff-898e737ee4e56ba042bda31764bed49e on master to fix Actions triggering.  Can you merge that update your branch and push up again?

**Comment by phiresky** [comment]
done. passes

**Comment by bradymholt** [comment]
Thanks!  I'll do a bit more manual testing and think through the defaults before publishing.

**Comment by phiresky** [comment]
thanks! can you say why the workflow configuration needed to be changed? it looked correct to me?

**Comment by bradymholt** [comment]
I've been making the same changes to my other projects because I was getting double triggers from the push and pull_request events.  But, it should have triggered with the previous change.  I think it might have just been delayed.

**Comment by bradymholt** [comment]
One additional change here: https://github.com/bradymholt/vscode-pgFormatter/pull/31.  I just published 1.13.0 which will be available in about 5 minutes.  Thanks again!

**Pull request merged**
